### ISSUE TITLE
The stored procedure get_expected_today could be written in python

### ISSUE THREAD

**Issue by ticosax** [k-nut/csa-share-management#43]
It doesn't accept any row as input and doesn't read anything in the db.
It just makes things more complex to maintain and to test.
@k-nut  Do you agree we could rewrite it in python ?

**Comment by k-nut** [comment]
I think there is a benefit in the current setup. We use the procedure in [`get_exptected_amount_map`](https://github.com/k-nut/csa-share-management/blob/d9126e71a3b40c4cb0bac42f41688e04586de26f/solawi/models.py#L276) where it is used to aggregate expected costs per share for all shares. Since that all happens in the db, it does save us from doing roundtrips to first fetch all of the bets and to then calculate the expected values. Does that make sense?

**Comment by ticosax** [comment]
right, in this context, yes, it makes sense. thanks for the explanation.
